### ISSUE TITLE
AMP converter

### ISSUE THREAD

**Issue by AMPtemplates** [paulredmond/html-to-amp#4]
HI Paul, great work and was wondering if and we could collaborate. Please find our try for a converter at http://amphtmlconverter.com . Happy to share. Please let us know your thoughts. Have a great day.

**Comment by paulredmond** [comment]
@AMPtemplates sure thing, let me know how you intend on contributing to this repo ahead of time so I can make sure your work is on the right track as far as this library is concerned.
