### ISSUE TITLE
Youtube converter error

### ISSUE THREAD

**Issue by lunglung876** [paulredmond/html-to-amp#5]
https://github.com/paulredmond/html-to-amp/blob/master/src/Converter/Extensions/YoutubeConverter.php#L36

Argument 2 of createWritableElement() must be array.

**Comment by paulredmond** [comment]
@lunglung876 thank you for the report 👌

**Comment by paulredmond** [comment]
Should be fixed in #6. Waiting to hear back on the Travis CI build and then I'll merge 👍
