### ISSUE TITLE
Why it is scoped at just body context?

### ISSUE THREAD

**Issue by chay22** [paulredmond/html-to-amp#8]
I think it's good enough to convert whole fragments in one go. I know it requires a lot more work. But, what do you say?

**Comment by paulredmond** [comment]
@chay22 can you be more specific? Maybe some code examples (inline or via https://gist.github.com/) could help me understand what you mean.

**Comment by chay22** [comment]
@paulredmond I read again my question, yeah it's  quite confusing, LOL.

Taken from readme.

> main purpose is parsing fragments of HTML content (an article body)

While this package is easy enough to extends, I think it's better to let this package does everything I'm currently need. What I means is, convert the whole content -- every `html` tag children . I was thinking on why you just focused in converting body area.

That's not a real issue, yes.

**Comment by chay22** [comment]
Anyways, I forked this repo and modify the logic a bit [here](https://github.com/chay22/html-to-amp/tree/dev). I wonder if you can get a better flow of what I was added. I'm quite lost at [this](https://github.com/chay22/html-to-amp/blob/dev/src/Spec.php#L121) (validating element's scope).

Basically, I'm going to whitelisting, not blacklisting -- like you did. And that's why I'm wondering if you were just validate/convert the whole elements, everything would be just fine.

**Comment by paulredmond** [comment]
Hey @chay22 just getting back to this. Anytime someone sends code/updates and raises an issue I appreciate it. Thank you.

For me, I followed the AMP guide and the blacklist removes prohibited elements. I think the blacklist is shorter than whitelisting every possible element, and even then, a document might have custom elements. The AMP guide is explicit about which elements are blacklisted so it makes sense to me that the code follows that guide.

If you can provide more examples and a PR I'd definitely take a look. Before going to that trouble maybe if you can provide before/after HTML document example (as basic as possible) to get your point across I can take a look and try to understand what you think would make this repo more useful.

I built this with only a need to convert articles, and the HTML skeleton around that content is AMP-compliant. **Honestly, to get AMP working your full HTML document will already need to have AMP Javascript**, no `<style>` tags (apart from the one allowed style tag), and it really doesn't make sense to convert anything but the `<body>`.
